apiVersion: fabric.deploy/v1alpha1
kind: FabricDeployment

metadata:
  deploymentId: gitactiontest-phase3

items:
  - logicalId: gitActionEnvironment
    type: Environment
    path: items/environments/gitactiontest

  - logicalId: gitActionNotebook
    type: Notebook
    path: items/notebooks/gitactiontest-hello
    dependsOn:
      - gitActionEnvironment

  - logicalId: gitActionLakehouse
    type: Lakehouse
    path: items/lakehouses/gitactiontest

  - logicalId: gitActionSparkJob
    type: SparkJobDefinition
    path: items/spark-jobs/logical-references
    dependsOn:
      - gitActionEnvironment
      - gitActionLakehouse
